apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.7.1
    helm.sh/chart: aws-load-balancer-controller-1.7.1
  name: aws-load-balancer-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRSjllUE1pUUVPazVVOXBLNjEydTY2akFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMApNRE13TkRFMk1EWXhPVm9YRFRNME1ETXdNakUyTURZeE9Wb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTDVpL0xMNTk2RE94M1h6MWp2eExWemRhUWovdU9rclR5TC9YSlcwNFEvNXJoZzRLKzUyMlRheApRM0FhbU9WcFNEU3l3dXRwNUJ5VXpTMnRYTEdKcEZqQ2w2ampPV0VoNGI4cm9Ha29WdmdGdDExeUVGdFBBRmVoCmVybXFwTkNXSG1yeXNFNG1JeGUzb2t4a1NvWlROd0dabmxsN29SU2J2OGhaeW9aSkI4dm5aTVBPSytTQSsyZUQKdDdFUHN3a25rMU9MNFNEdUZ5N0dpQkxJUndKbVk5cHk3Nk1ER2VkRE5lQ0JyenR5Wlk2TkMvUU1RQjEzN2FZaQpGeDNhZ3IwaGlraC9zQzhPRGVKTWVQbGNtT0tsK0pMT1dOc2l6K3pHVkY3ZFgwNFNuQzdQU05DRGdMSXliU2c3CmU5cCtvbEV0bnVsMXNIOTlmZ2pHbi9JdnZoenVnZWNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlNpQ3h3SW1ZQXZ5cnJ4bHVOMlZjcTEwMlo2YmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFDSkpJWXdHandkVTMwM21mYmZ6YjNhd3djTkFUaTdSTE5mM3dJTnNsaG1LKzZudzhKdFI1OUFZSjV1d1EKek1ha1MyK0dKbUNleVkxcXcxd041ZzlTYU5QRXJWbTZPMFpqYkZmM2o0WEhkcnV0ZVdCMmtGRkpmeE44NVF6Zwp3ekQvTWkyQzlleDNLeFNRbkJlRFVpV2NKd0Fmd0Ywa3VvOGMvNmF3WFJZK0FSd0ZFZFBoT0dQckJmNlRrOFRrClhEWEdoV2JHbFJiekRvVllseS9mZEF0dVBkVWR1a3dscWRTb1hlc3VUQk9pYmFySG92S1lxeFBoWXNZcGprbkQKclVuY25xeUtRdTZ3akYyOVY3UG0waklsS2FsSm5Tdnd2R0oyb0tadmREUytpY08yQ2l6dUV1Q3ZoZ0dydVB1agpiZC83SFBwVFpNSUdIV1lqRW5kM3NRT3FIZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.elbv2.k8s.aws
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/pod-readiness-gate-inject
      operator: In
      values:
      - enabled
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRSjllUE1pUUVPazVVOXBLNjEydTY2akFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMApNRE13TkRFMk1EWXhPVm9YRFRNME1ETXdNakUyTURZeE9Wb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTDVpL0xMNTk2RE94M1h6MWp2eExWemRhUWovdU9rclR5TC9YSlcwNFEvNXJoZzRLKzUyMlRheApRM0FhbU9WcFNEU3l3dXRwNUJ5VXpTMnRYTEdKcEZqQ2w2ampPV0VoNGI4cm9Ha29WdmdGdDExeUVGdFBBRmVoCmVybXFwTkNXSG1yeXNFNG1JeGUzb2t4a1NvWlROd0dabmxsN29SU2J2OGhaeW9aSkI4dm5aTVBPSytTQSsyZUQKdDdFUHN3a25rMU9MNFNEdUZ5N0dpQkxJUndKbVk5cHk3Nk1ER2VkRE5lQ0JyenR5Wlk2TkMvUU1RQjEzN2FZaQpGeDNhZ3IwaGlraC9zQzhPRGVKTWVQbGNtT0tsK0pMT1dOc2l6K3pHVkY3ZFgwNFNuQzdQU05DRGdMSXliU2c3CmU5cCtvbEV0bnVsMXNIOTlmZ2pHbi9JdnZoenVnZWNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlNpQ3h3SW1ZQXZ5cnJ4bHVOMlZjcTEwMlo2YmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFDSkpJWXdHandkVTMwM21mYmZ6YjNhd3djTkFUaTdSTE5mM3dJTnNsaG1LKzZudzhKdFI1OUFZSjV1d1EKek1ha1MyK0dKbUNleVkxcXcxd041ZzlTYU5QRXJWbTZPMFpqYkZmM2o0WEhkcnV0ZVdCMmtGRkpmeE44NVF6Zwp3ekQvTWkyQzlleDNLeFNRbkJlRFVpV2NKd0Fmd0Ywa3VvOGMvNmF3WFJZK0FSd0ZFZFBoT0dQckJmNlRrOFRrClhEWEdoV2JHbFJiekRvVllseS9mZEF0dVBkVWR1a3dscWRTb1hlc3VUQk9pYmFySG92S1lxeFBoWXNZcGprbkQKclVuY25xeUtRdTZ3akYyOVY3UG0waklsS2FsSm5Tdnd2R0oyb0tadmREUytpY08yQ2l6dUV1Q3ZoZ0dydVB1agpiZC83SFBwVFpNSUdIV1lqRW5kM3NRT3FIZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-service
  failurePolicy: Fail
  name: mservice.elbv2.k8s.aws
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - services
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRSjllUE1pUUVPazVVOXBLNjEydTY2akFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMApNRE13TkRFMk1EWXhPVm9YRFRNME1ETXdNakUyTURZeE9Wb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTDVpL0xMNTk2RE94M1h6MWp2eExWemRhUWovdU9rclR5TC9YSlcwNFEvNXJoZzRLKzUyMlRheApRM0FhbU9WcFNEU3l3dXRwNUJ5VXpTMnRYTEdKcEZqQ2w2ampPV0VoNGI4cm9Ha29WdmdGdDExeUVGdFBBRmVoCmVybXFwTkNXSG1yeXNFNG1JeGUzb2t4a1NvWlROd0dabmxsN29SU2J2OGhaeW9aSkI4dm5aTVBPSytTQSsyZUQKdDdFUHN3a25rMU9MNFNEdUZ5N0dpQkxJUndKbVk5cHk3Nk1ER2VkRE5lQ0JyenR5Wlk2TkMvUU1RQjEzN2FZaQpGeDNhZ3IwaGlraC9zQzhPRGVKTWVQbGNtT0tsK0pMT1dOc2l6K3pHVkY3ZFgwNFNuQzdQU05DRGdMSXliU2c3CmU5cCtvbEV0bnVsMXNIOTlmZ2pHbi9JdnZoenVnZWNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlNpQ3h3SW1ZQXZ5cnJ4bHVOMlZjcTEwMlo2YmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFDSkpJWXdHandkVTMwM21mYmZ6YjNhd3djTkFUaTdSTE5mM3dJTnNsaG1LKzZudzhKdFI1OUFZSjV1d1EKek1ha1MyK0dKbUNleVkxcXcxd041ZzlTYU5QRXJWbTZPMFpqYkZmM2o0WEhkcnV0ZVdCMmtGRkpmeE44NVF6Zwp3ekQvTWkyQzlleDNLeFNRbkJlRFVpV2NKd0Fmd0Ywa3VvOGMvNmF3WFJZK0FSd0ZFZFBoT0dQckJmNlRrOFRrClhEWEdoV2JHbFJiekRvVllseS9mZEF0dVBkVWR1a3dscWRTb1hlc3VUQk9pYmFySG92S1lxeFBoWXNZcGprbkQKclVuY25xeUtRdTZ3akYyOVY3UG0waklsS2FsSm5Tdnd2R0oyb0tadmREUytpY08yQ2l6dUV1Q3ZoZ0dydVB1agpiZC83SFBwVFpNSUdIV1lqRW5kM3NRT3FIZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: mtargetgroupbinding.elbv2.k8s.aws
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
