apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v2.7.1
    helm.sh/chart: aws-load-balancer-controller-1.7.1
  name: aws-load-balancer-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU92aDF5WkNJOVRjNkRhWUlOWFhFVll3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREF6TURVd09UVXdNVFJhRncwek5EQXpNRE13T1RVd01UUmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURxdlN2TFg3V3pLVlcrbmdXcHlLdXUvd01ZaVQwYjFQK1hGVGZqMmpZckV3bHB0MGl2UU5nRwpIVUF0YjcvUzZOVXNDcmw0QUNoa3pDbk1jNWFjRjYyNnZvTWd6VkUwUHRIeXMvMVBKU3pid1FyNjlwWjVJUlVNClFSS28wZ1NoWkdpWXJjcWpzdmk3ZUJ2WFpjSzZtSy83N3orSFBMcnE4dE9wcjJWTWJsTFd1cW15eHd3VWRWY28KWGh3a0RUdU9iKzM0OTAxRzJCOFFoa0wwSnhaTTZJeXVFY3ByRnBaaFRjUjI4ekkvWC9XVXhPYkJYeXhJOHJsTwpuRlRFRFZKYStwT2RZTlBKRUlLcWloSVNGOENIVENVRk9TdGFZKytCUllYVjZLeDdrYWNZb211eU1jQUJFV2tKCk1pckg5bFlBVEM1UGlKTFV4S1dmUytLOEtQSENPSnlEQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVWmdTSEFmVXp6cnpQZng3QmZETHhpS3V6S21Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTi9VZGtxTHBPcXVpRFl6eDdwOVV4WDlvSjgva3dZSUoxbk5tamlvM2lHNEQ0S3VHQmd2ZVZGUUJoQ2wKZXk5bkN4OUhRSFF0TnFhWUZicGlORUFIQmNBOGJrSjE5Qk5RcENBM1puWXczdE1tNHVnSzZLVjJDTXFwQnFZNgowOTY0emkxT1Q2d01rMHg5UDRrb1kvdVFuWFFvdGRzVnNyMzFMUTlzOVU4S09GUTNFQzkxZGZGUXhRN2l2bUFiCnFVdStrbnp5Rk9wRVNmTHlrRWIxbmN4MzU2MUtnOWE5bjh6SlFTWmgzRVJUZU9PRnRlZGFKTC90K1lRYXpINnEKMnV6QmpQOEYwQ1NvMmVWejZYNmM4OVNGN0ZYNS9GUGh6ZENidDBpcnFnREdDbjFGUUZYdk5VbEFiT3JMbWo2dwpiak9EdVRtN3FBL25QekwwUXUzcU51UUNLVUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
  failurePolicy: Fail
  name: vingressclassparams.elbv2.k8s.aws
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressclassparams
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU92aDF5WkNJOVRjNkRhWUlOWFhFVll3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREF6TURVd09UVXdNVFJhRncwek5EQXpNRE13T1RVd01UUmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURxdlN2TFg3V3pLVlcrbmdXcHlLdXUvd01ZaVQwYjFQK1hGVGZqMmpZckV3bHB0MGl2UU5nRwpIVUF0YjcvUzZOVXNDcmw0QUNoa3pDbk1jNWFjRjYyNnZvTWd6VkUwUHRIeXMvMVBKU3pid1FyNjlwWjVJUlVNClFSS28wZ1NoWkdpWXJjcWpzdmk3ZUJ2WFpjSzZtSy83N3orSFBMcnE4dE9wcjJWTWJsTFd1cW15eHd3VWRWY28KWGh3a0RUdU9iKzM0OTAxRzJCOFFoa0wwSnhaTTZJeXVFY3ByRnBaaFRjUjI4ekkvWC9XVXhPYkJYeXhJOHJsTwpuRlRFRFZKYStwT2RZTlBKRUlLcWloSVNGOENIVENVRk9TdGFZKytCUllYVjZLeDdrYWNZb211eU1jQUJFV2tKCk1pckg5bFlBVEM1UGlKTFV4S1dmUytLOEtQSENPSnlEQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVWmdTSEFmVXp6cnpQZng3QmZETHhpS3V6S21Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTi9VZGtxTHBPcXVpRFl6eDdwOVV4WDlvSjgva3dZSUoxbk5tamlvM2lHNEQ0S3VHQmd2ZVZGUUJoQ2wKZXk5bkN4OUhRSFF0TnFhWUZicGlORUFIQmNBOGJrSjE5Qk5RcENBM1puWXczdE1tNHVnSzZLVjJDTXFwQnFZNgowOTY0emkxT1Q2d01rMHg5UDRrb1kvdVFuWFFvdGRzVnNyMzFMUTlzOVU4S09GUTNFQzkxZGZGUXhRN2l2bUFiCnFVdStrbnp5Rk9wRVNmTHlrRWIxbmN4MzU2MUtnOWE5bjh6SlFTWmgzRVJUZU9PRnRlZGFKTC90K1lRYXpINnEKMnV6QmpQOEYwQ1NvMmVWejZYNmM4OVNGN0ZYNS9GUGh6ZENidDBpcnFnREdDbjFGUUZYdk5VbEFiT3JMbWo2dwpiak9EdVRtN3FBL25QekwwUXUzcU51UUNLVUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: vtargetgroupbinding.elbv2.k8s.aws
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU92aDF5WkNJOVRjNkRhWUlOWFhFVll3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREF6TURVd09UVXdNVFJhRncwek5EQXpNRE13T1RVd01UUmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURxdlN2TFg3V3pLVlcrbmdXcHlLdXUvd01ZaVQwYjFQK1hGVGZqMmpZckV3bHB0MGl2UU5nRwpIVUF0YjcvUzZOVXNDcmw0QUNoa3pDbk1jNWFjRjYyNnZvTWd6VkUwUHRIeXMvMVBKU3pid1FyNjlwWjVJUlVNClFSS28wZ1NoWkdpWXJjcWpzdmk3ZUJ2WFpjSzZtSy83N3orSFBMcnE4dE9wcjJWTWJsTFd1cW15eHd3VWRWY28KWGh3a0RUdU9iKzM0OTAxRzJCOFFoa0wwSnhaTTZJeXVFY3ByRnBaaFRjUjI4ekkvWC9XVXhPYkJYeXhJOHJsTwpuRlRFRFZKYStwT2RZTlBKRUlLcWloSVNGOENIVENVRk9TdGFZKytCUllYVjZLeDdrYWNZb211eU1jQUJFV2tKCk1pckg5bFlBVEM1UGlKTFV4S1dmUytLOEtQSENPSnlEQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVWmdTSEFmVXp6cnpQZng3QmZETHhpS3V6S21Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTi9VZGtxTHBPcXVpRFl6eDdwOVV4WDlvSjgva3dZSUoxbk5tamlvM2lHNEQ0S3VHQmd2ZVZGUUJoQ2wKZXk5bkN4OUhRSFF0TnFhWUZicGlORUFIQmNBOGJrSjE5Qk5RcENBM1puWXczdE1tNHVnSzZLVjJDTXFwQnFZNgowOTY0emkxT1Q2d01rMHg5UDRrb1kvdVFuWFFvdGRzVnNyMzFMUTlzOVU4S09GUTNFQzkxZGZGUXhRN2l2bUFiCnFVdStrbnp5Rk9wRVNmTHlrRWIxbmN4MzU2MUtnOWE5bjh6SlFTWmgzRVJUZU9PRnRlZGFKTC90K1lRYXpINnEKMnV6QmpQOEYwQ1NvMmVWejZYNmM4OVNGN0ZYNS9GUGh6ZENidDBpcnFnREdDbjFGUUZYdk5VbEFiT3JMbWo2dwpiak9EdVRtN3FBL25QekwwUXUzcU51UUNLVUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-networking-v1-ingress
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vingress.elbv2.k8s.aws
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
