apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  namespace: kube-system
spec:
  amiFamily: AL2
  role: karpenter-blue-20240214145158250000000005
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: blue
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: blue
