apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  namespace: kube-system
spec:
  template:
    disruption:
      consolidationPolicy: WhenUnderutilized
      expireAfter: 1h
    limits:
      cpu: 1000
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: '["amd64"]'
      - key: kubernetes.io/os
        operator: In
        values: '["linux"]'
      - key: karpenter.sh/capacity-type
        operator: In
        values: '["on-demand"]'
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: '["c", "m", "r"]'
      - key: kubernetes.io/arch
        operator: Gt
        values: '["2"]'
