apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: karpenter-v0.34.0
  name: karpenter
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 8000
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/name: karpenter
  type: ClusterIP
