apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: karpenter-v0.34.0
  name: karpenter
  namespace: kube-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - karpenter-leader-election
  resources:
  - leases
  verbs:
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
